### ISSUE TITLE
[BUG]Gitea无法在安装时选择MariaDB数据库

### ISSUE THREAD

**Issue by 7980963** [1Panel-dev/1Panel#2517]
### 1Panel 版本

v1.6.2

### 问题描述

Wordpress安装的时候是可以正常选的，数据库也正常

### 重现步骤

应用商店安装Gitea

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本支持安装 Gitea 时选择 MariaDB 数据库。

**Comment by wc7086** [comment]
重复 #1978

**Comment by willow-god** [comment]
您好，Gitea目前似乎又不允许选择mariadb了，可以再支持一下吗？

**Comment by wanghe-fit2cloud** [comment]
好的，我们近期适配一下。

**Comment by willow-god** [comment]
![Image](https://github.com/user-attachments/assets/04f576f3-6c16-4ddc-91a6-0667b37def04)

嗯嗯好的，谢谢，麻烦开发者了，目前我查到的资料确实是支持MariaDB的，并且还支持SQLite等其他数据库，所以应该是可以的。

其实我感觉可以把数据库分类中，MySQL和MariaDB放在一类进行选择，因为他们两个有很强的兼容性，至于一小部分的不兼容我感觉可以让大家自行斟酌

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![Image](https://github.com/user-attachments/assets/04f576f3-6c16-4ddc-91a6-0667b37def04)

Well, okay, thank you, I'm sorry, the developer. The information I've found currently does support MariaDB and also supports other databases such as SQLite, so it should be OK.

Actually, I feel that in the database classification, MySQL and MariaDB can be selected in the same category, because they have strong compatibility. As for a small number of incompatibility, I feel that everyone can consider it for themselves.

**Comment by wanghe-fit2cloud** [comment]
> 您好，Gitea目前似乎又不允许选择mariadb了，可以再支持一下吗？

已支持。
