### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by system-help-solution** [1Panel-dev/1Panel#3153]
### 请描述您的问题

嗨，你好吗？我是巴西人，我正在使用 Google 翻译。 我喜欢这个项目，但我无法理解从源代码安装 Aparti 项目背后的逻辑。您可以带一个迷你教程，或者也许将命令留在支持页面上。 预先非常感谢您的关注

**Comment by zhengkunwang223** [comment]
> ### 请描述您的问题
> 嗨，你好吗？我是巴西人，我正在使用 Google 翻译。 我喜欢这个项目，但我无法理解从源代码安装 Aparti 项目背后的逻辑。您可以带一个迷你教程，或者也许将命令留在支持页面上。 预先非常感谢您的关注

不好意思 我不能完全理解你的意思 或许你可以用你熟悉的语言 然后我来翻译

**Comment by system-help-solution** [comment]
Certo vou usar o português Brasil para falar. 
Estou tentando fazer a instalação via o código fonte porem tento o fórum tanto aqui no Github não achei  a forma de fazer a instalação direto do código fonte. Até tentei usar como base o instalador.sh e mesmo assim não consegui.

Oque eu queria de possível uma luz para eu poder i stalar Aparti do código do código fonte .

**Comment by wanghe-fit2cloud** [comment]
> Certo vou usar o português Brasil para falar. Estou tentando fazer a instalação via o código fonte porem tento o fórum tanto aqui no Github não achei a forma de fazer a instalação direto do código fonte. Até tentei usar como base o instalador.sh e mesmo assim não consegui.
> 
> Oque eu queria de possível uma luz para eu poder i stalar Aparti do código do código fonte .

Por favor, consulte a documentação oficial para obter informações detalhadas sobre como configurar o ambiente de desenvolvimento.
https://1panel.cn/docs/dev_manual/dev_manual/

**Comment by system-help-solution** [comment]
Certo mesmo vendo  esse documento ainda ficou muito vago . Sei que o tempo de vocês são preciosos mas infelizmente eu não tô conseguindo entender . Caso me ajudar estou disposto a fazer um tutorial de INSTALAÇÃO para quem quiser instalar através do código fonte isso seria a minha ajuda para o projeto. Sem contar que estou disposto a  trazer algumas das minha solução para esse projeto.

**Comment by wanghe-fit2cloud** [comment]
> Certo mesmo vendo esse documento ainda ficou muito vago . Sei que o tempo de vocês são preciosos mas infelizmente eu não tô conseguindo entender . Caso me ajudar estou disposto a fazer um tutorial de INSTALAÇÃO para quem quiser instalar através do código fonte isso seria a minha ajuda para o projeto. Sem contar que estou disposto a trazer algumas das minha solução para esse projeto.

Após ler este artigo, você pode detalhar os problemas específicos encontrados ao configurar o ambiente de desenvolvimento usando o código-fonte?

**Comment by system-help-solution** [comment]
Certo irei refazer aqui e já volto .

**Comment by jefferson-system-help-oficial** [comment]
![Screenshot_20231203-161357_Brave](https://github.com/1Panel-dev/1Panel/assets/152101129/d64145f0-d5e9-4208-92ef-0acc4bd59933)
quando eu fasso com ocodio fonte esse e os erros


logs

> 1Panel-Frontend@1.7.0 dev /root/1panel/1Panel/frontend
> vite


  vite v2.9.16 dev server running at:

  > Local:    http://localhost:4004/
  > Network:  http://37.27.21.222:4004/
  > Network:  http://172.24.0.1:4004/

  ready in 636ms.

files in the public directory are served at the root path.
Instead of /public/favicon.png, use /favicon.png.
7:15:46 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
7:15:46 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) (x2)
7:15:46 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) (x3)
7:15:46 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) (x4)
7:15:46 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) (x5)
7:15:46 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) (x6)
7:16:06 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) (x7)
