### ISSUE TITLE
应用商店安装redis一直重启中

### ISSUE THREAD

**Issue by wm475390847** [1Panel-dev/1Panel#3195]
### 一直在重启

![POPO-20231205-191450](https://github.com/1Panel-dev/1Panel/assets/68719907/3f75f9bc-7ab9-45ee-8e98-573655990fb5)

**Comment by wanghe-fit2cloud** [comment]
错误日志有提示权限问题，再提供一下 1Panel 服务器操作系统具体版本、登录用户和 SELinux 是否已关闭等信息。

**Comment by wanghe-fit2cloud** [comment]
先关闭该 Issue 了，如有问题再继续讨论。

**Comment by wm475390847** [comment]
好的

**Comment by demonyins** [comment]
在离线环境下 报错 环境变量中看到有下载 http://download.redis.io/releases/redis-7.2.3.tar.gz 

redis7  | 1:C 09 Jan 2024 11:25:22.840 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis7  | 1:C 09 Jan 2024 11:25:22.841 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis7  | 1:C 09 Jan 2024 11:25:22.841 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis7  | 1:C 09 Jan 2024 11:25:22.841 * Configuration loaded
redis7  | 1:M 09 Jan 2024 11:25:22.841 * monotonic clock: POSIX clock_gettime
redis7  | 1:M 09 Jan 2024 11:25:22.843 # Failed to write PID file: Permission denied
redis7  | 1:M 09 Jan 2024 11:25:22.843 * Running mode=standalone, port=6379.
redis7  | 1:M 09 Jan 2024 11:25:22.843 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis7  | 1:M 09 Jan 2024 11:25:22.843 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis7 exited with code 1
redis7  | 1:C 09 Jan 2024 11:25:22.840 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis7  | 1:C 09 Jan 2024 11:25:22.841 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis7  | 1:C 09 Jan 2024 11:25:22.841 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis7  | 1:C 09 Jan 2024 11:25:22.841 * Configuration loaded
redis7  | 1:M 09 Jan 2024 11:25:22.841 * monotonic clock: POSIX clock_gettime
redis7  | 1:M 09 Jan 2024 11:25:22.843 # Failed to write PID file: Permission denied
redis7  | 1:M 09 Jan 2024 11:25:22.843 * Running mode=standalone, port=6379.
redis7  | 1:M 09 Jan 2024 11:25:22.843 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis7  | 1:M 09 Jan 2024 11:25:22.843 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis7 exited with code 1
